name: docker4640

on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          include:
            - dockerfile: ./app/Dockerfile
              image: ${{ DOCKERHUB_USERNAME }}/app
            - dockerfile: ./web/Dockerfile
              image: ${{ DOCKERHUB_USERNAME }}/web
    steps:
    - 
      name: Checkout the code
      uses: actions/checkout@v3 
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: adelkuanysheva/demo4640:latest  
          context: ./app
          file: ${{ matrix.dockerfile }}
