name: docker4640

on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    matrix:
        include:
          - dockerfile: ./app/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/app
          - dockerfile: ./web/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/web
    steps:
    - 
      name: Checkout the code
      uses: actions/checkout@v3 
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: adelkuanysheva/demo4640:latest  
          context: .
          file: ${{ matrix.dockerfile }}
